---
# tasks file for ansible-timedatectl
- name: Setup timesync config
  template:
    src: timesyncd.conf.template
    dest: /etc/systemd/timesyncd.conf
  notify: run Timedatectl

- name: set Timezone
  timezone: name={{ timedatectl_timezone }}
